# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2cfce8156b2153003c1171240f73abb7a1896573eaa5834cc9b12a261ec5b5c9e268b8e45aa945a68665e43dcbbc7598b537a0462c439f649053eac8a8567c63

test:
  secret_key_base: ff4ca5ce2108a6e49bf540db00846233fe3bf66b7c9f0b13ea53109c5572c0068426e48ea3cbffc605fb5ff1ea0f30349152bc9c89366d13e2660793c7040ce7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
